# Generated by Django 4.2.17 on 2025-02-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='slug',
        ),
    ]
