# Generated by Django 4.2.17 on 2025-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0002_remove_pettype_slug_remove_servicetype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petbusiness',
            name='canton',
            field=models.CharField(choices=[('Genève', 'Genève'), ('Vaud - La Côte', 'Vaud - La Côte'), ('Vaud - Lausanne', 'Vaud - Lausanne'), ('Vaud - Gros-de-Vaud & Plaine de l’Orbe', 'Vaud - Gros-de-Vaud & Plaine de l’Orbe'), ('Vaud - Riviera & Chablais', 'Vaud - Riviera & Chablais'), ('Vaud - Nord vaudois', 'Vaud - Nord vaudois'), ('Valais', 'Valais'), ('Fribourg', 'Fribourg'), ('Neuchâtel', 'Neuchâtel'), ('Jura', 'Jura')], max_length=100),
        ),
    ]
