# Generated by Django 4.2.17 on 2025-02-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0003_alter_petbusiness_canton'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettype',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
