# Generated by Django 4.2.17 on 2025-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0004_petbusiness_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='petbusiness',
            name='canton',
            field=models.CharField(choices=[('Genève', 'Genève'), ('Vaud - La Côte', 'Vaud - La Côte'), ('Vaud - Gros-de-Vaud & Plaine de l’Orbe', 'Vaud - Gros-de-Vaud & Plaine de l’Orbe'), ('Vaud - Alpes vaudoises & Chablais vaudois', 'Vaud - Alpes vaudoises & Chablais vaudois'), ('Vaud - Jura vaudois', 'Vaud - Jura vaudois'), ('Valais', 'Valais'), ('Fribourg', 'Fribourg'), ('Neuchâtel', 'Neuchâtel'), ('Jura', 'Jura')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
