# Generated by Django 4.2.17 on 2025-03-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0004_pettype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettype',
            name='slug',
        ),
    ]
