# Generated by Django 4.2.17 on 2025-02-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0005_petbusiness_canton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petbusiness',
            name='canton',
            field=models.CharField(choices=[('Genève', 'Genève'), ('Vaud - La Côte', 'Vaud - La Côte'), ('Vaud - Lausanne', 'Vaud - Lausanne'), ('Vaud - Gros-de-Vaud & Plaine de l’Orbe', 'Vaud - Gros-de-Vaud & Plaine de l’Orbe'), ('Vaud - Alpes vaudoises & Chablais vaudois', 'Vaud - Alpes vaudoises & Chablais vaudois'), ('Vaud - Jura vaudois', 'Vaud - Jura vaudois'), ('Valais', 'Valais'), ('Fribourg', 'Fribourg'), ('Neuchâtel', 'Neuchâtel'), ('Jura', 'Jura')], max_length=100),
        ),
    ]
