# Generated by Django 4.2.17 on 2025-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0006_alter_petbusiness_canton'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
