# Generated by Django 4.2.17 on 2025-04-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_order_street_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlineitem_activation_code', to='checkout.orderlineitem')),
            ],
        ),
    ]
