# Generated by Django 4.2.17 on 2025-04-15 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0004_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
