# Generated by Django 4.2.17 on 2025-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_activationcode_activated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, choices=[('CH', 'Suisse'), ('LI', 'Liechtenstein')], default='CH', max_length=80, null=True),
        ),
    ]
