# Generated by Django 4.2.17 on 2025-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petowner',
            old_name='date_created',
            new_name='default_date_created',
        ),
        migrations.RenameField(
            model_name='petowner',
            old_name='last_modified',
            new_name='default_last_modified',
        ),
        migrations.RenameField(
            model_name='petowner',
            old_name='newsletter',
            new_name='default_newsletter',
        ),
        migrations.RenameField(
            model_name='petowner',
            old_name='phone',
            new_name='default_phone',
        ),
        migrations.AddField(
            model_name='petowner',
            name='default_city',
            field=models.CharField(default='Genève', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petowner',
            name='default_country',
            field=models.CharField(blank=True, default='Suisse', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='petowner',
            name='default_postal_code',
            field=models.CharField(default='1205', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petowner',
            name='default_street',
            field=models.CharField(default='Rue de Lausanne', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petowner',
            name='default_street_number',
            field=models.CharField(default='23', max_length=10),
            preserve_default=False,
        ),
    ]
