# Generated by Django 4.2.17 on 2025-02-18 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
