# Generated by Django 4.2.17 on 2025-04-03 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0005_remove_pettype_slug'),
        ('pet_owners', '0002_rename_date_created_petowner_default_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pet_businesses.pettype'),
        ),
    ]
