# Generated by Django 4.2.17 on 2025-04-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0003_alter_pet_birthday_alter_pet_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner',
            name='default_street_number',
        ),
    ]
