# Generated by Django 4.2.17 on 2025-04-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_owners', '0004_remove_petowner_default_street_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_owner',
        ),
        migrations.AddField(
            model_name='pet',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pet_owners_pets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
