# Generated by Django 4.2.17 on 2025-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0005_remove_pet_pet_owner_pet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='default_country',
            field=models.CharField(blank=True, choices=[('CH', 'Suisse'), ('LI', 'Liechtenstein')], default='CH', max_length=80, null=True),
        ),
    ]
