# Generated by Django 4.2.17 on 2025-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0006_alter_petowner_default_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='default_country',
            field=models.CharField(choices=[('CH', 'Suisse'), ('LI', 'Liechtenstein')], default='CH', max_length=80),
        ),
    ]
