# Generated by Django 4.2.17 on 2025-02-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_businesses', '0003_alter_petbusiness_canton'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=12, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expires', models.DateTimeField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='vouchers/pdfs/')),
                ('pet_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='pet_businesses.petbusiness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('user', 'pet_business', 'discount_type'), name='unique_voucher_per_business'),
        ),
    ]
