# Generated by Django 4.2.17 on 2025-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='status',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/'),
        ),
    ]
