# Generated by Django 4.2.17 on 2025-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_voucher_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='pdf_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
