# Generated by Django 4.2.17 on 2025-03-05 15:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_alter_voucher_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
    ]
